### ISSUE TITLE
404 on latest (15.2)

### ISSUE THREAD

**Issue by da3dsoul** [crazy-max/docker-nextcloud#11]
I don't know what the issue is. The logs say it's up, but it gives the traefik 404 message. It worked before I `docker-compose up -d`'d

I don't know what other info might help, so let me know. It's on ubuntu 16.04

**Comment by crazy-max** [comment]
Maybe linked to [this](https://github.com/crazy-max/docker-nextcloud/issues/9#issuecomment-453567509) ?

**Comment by da3dsoul** [comment]
I literally just noticed that before coming back here.
```
traefik:
    image: traefik:1.6-alpine
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=somedomainsthataremine+localhost"
      - "--acme=false"
      - "--acme.acmelogging=true"
      - "--acme.email=redacted"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 8000
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
```
Would that be the proper way to go about fixing it?
