### ISSUE TITLE
Is a TURN server built-in for Nextcloud Talk?

### ISSUE THREAD

**Issue by Spass1966** [crazy-max/docker-nextcloud#15]
Quoted from https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794:

> In some cases, e.g. in combination with firewalls or symmetric NAT 110 a STUN server will not work as well, and then a so called TURN 118 server is needed. Now no direct P2P connection is established, but all traffic is relayed through the TURN server, thus additional (at least internal) traffic and resources are needed.

I have attempted to host Nextcloud (using other images) before but unfortunately either I can't see or the participant can't see video of the other. Every Dockerized Nextcloud I've come across doesn't package a solution in. My own attempts have ended in failure.

**Comment by Spass1966** [comment]
Also fully willing to put a bounty on this!

**Comment by Spass1966** [comment]
Doesn't look like it. I spent all day trying to magick up a solution and I've gotten nowhere.

For anyone interested here's the relevant piece of my `docker-compose.yaml`:
```
  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    tmpfs:
      - /var/lib/coturn
    volumes:
      - "./coturn/turnserver.conf:/etc/coturn/turnserver.conf"
    network_mode: "host"
```
and my `turnserver.conf`:
```
tls-listening-port=5349
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=supersecretpassphrase
realm=talk.hansen.agency
total-quota=100
bps-capacity=0
stale-nonce
```
cert=/etc/letsencrypt/live/talk.hansen.agency/fullchain.pem
pkey=/etc/letsencrypt/live/talk.hansen.agency/privkey.pem
cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"
no-loopback-peers
no-multicast-peers
