### ISSUE TITLE
Collabora not working: Saved with error..

### ISSUE THREAD

**Issue by MacGyver27** [crazy-max/docker-nextcloud#17]
When saving settings for Collabora I am getting:
`Saved with error: Collabora Online should use the same protocol as the server installation. `

When opening **odp** or **ods** document nothing happens, just blank loading screen..

Logs:
```
Error	lib	ResourceLocator can not find a web root (root: /data/userapps/richdocuments, file: css/richdocuments/5946-8205-admin.css?v=db81cddf52fdb3c8ca1e4c859e214124, webRoot: , throw: true)

Error	lib	ResourceLocator can not find a web root (root: /data/userapps/richdocuments, file: css/richdocuments/5946-8205-admin.css?v=db81cddf52fdb3c8ca1e4c859e214124, webRoot: , throw: true)

...
```

Versions:
Nextcloud: latest
Collabora: latest

FQDN:
Nextcloud: cloud.example.com
Collabora: collabora.cloud.example.com

![image](https://user-images.githubusercontent.com/6546231/56733579-da63b680-6760-11e9-8a4a-37b1ef1f1cd8.png)

Any ideas? Posted on the official nextcloud forum no response after over a month..
Thanks a lot, Michal

**Comment by crazy-max** [comment]
As I said in #10, I was not able to have a working collabora using https. Feel free to create a PR if you found a working solution.

**Comment by MacGyver27** [comment]
thanks for quick response.. anyway this goes a bit further.. I tried to set it up using just HTTP and same behavior..

```yml
  collabora:
    container_name: nextcloud.524.collabora
    image: collabora/code
    restart: always
    cap_add:
      - MKNOD
    expose:
      - 9980
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.port=9980"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:collabora.cloud.example.com"
      - "traefik.backend=nextcloud.524.collabora"
    environment:
      - "domain=cloud.example.com"
      - "DONT_GEN_SSL_CERT=true"
      - "extra_params=--disable-ssl"
```

Tried setting up the direct service: 
`http://collabora:9980`
Tried using `http` entry point as you have in docker-compose
`http://collabora.cloud.example.com`

Both above generates the following log every time I click on _office_ file:

`ResourceLocator can not find a web root (root: /data/userapps/richdocuments, file: css/richdocuments/426a-8205-viewer.css?v=db81cddf52fdb3c8ca1e4c859e214124, webRoot: , throw: true)`

Any idea what I might be doing wrong please?
Thanks again
