### ISSUE TITLE
WebDAV & Traefik subfolder

### ISSUE THREAD

**Issue by Numline1** [crazy-max/docker-nextcloud#7]
Hello! First of all, thanks for an awesome package, I finally managed to find one decent and working docker image for Nextcloud!

I'm running my own docker compose setup. The Nextcloud container is running in a subfolder at https://local.domain/nextcloud. I managed to use Traefik for this, the config looks something like this:

```
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.port=80"
      - "traefik.frontend.redirect.regex=^(.*)/nextcloud$$"
      - "traefik.frontend.redirect.replacement=$$1/nextcloud/"
      - "traefik.frontend.rule=PathPrefix: /nextcloud; ReplacePathRegex: ^/nextcloud/(.*) /$$1"
```

All was fine until this point, until I tried to use WebDAV. The example from this repo didn't quite cut it, since it's meant to be used for a subdomain, not a subfolder. Besides, the current rules should suffice.

Then I did some digging and found nginx.conf which has these lines in it:

```
        location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
        location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
```

which basically forces the redirect back to "/" (https://local.domain/remote.php/dav) instead of /nextcloud/...

There is currently no way to rewrite this rule. I had to cat the nginx.conf file, save it on a host, update it to be something like this:

```
        location = /.well-known/carddav {
            return 301 $scheme://$host/nextcloud/remote.php/dav;
        location = /.well-known/caldav {
            return 301 $scheme://$host/nextcloud/remote.php/dav;
```

and then mount it, read only, because it kept getting rewritten, and that solved the issue.

Proposed solution: Either finding a traefik rule that would work or allowing an env variable that'd be able to do this dynamically.

The other issue I found is basically forcing HSTS. This kinda screwed me over, because it feels slightly too opinionated for a Nextcloud image to force HSTS (and permanent redirects as well, although that's more understandable). It resulted in my entire domain being HSTS enabled, which blocked an access to non-TLS services, including Traefik Web UI :(

Anyway, that's all my feedback, hopefully something can be worked out :) Thanks again!

**Comment by crazy-max** [comment]
Hi @Numline1, indeed if you use this image under a subfolder it can hurt :)
I think the env var can fix this. I will do some digging aroung this. Thanks for your input.

**Comment by crazy-max** [comment]
Ok according to https://docs.nextcloud.com/server/stable/admin_manual/issues/general_troubleshooting.html#service-discovery we have to handle subfolder if defined.

**Comment by crazy-max** [comment]
@Numline1 Ok, can you post your traefik rules and nginx.conf ? I'm working on a better way to impl this.

**Comment by Numline1** [comment]
Hey @crazy-max and happy holidays :) Sure, here's my docker-compose section for Nextcloud (I removed the MariaDB, Redis and cron parts)

```
    image: crazymax/nextcloud:latest
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    volumes:
      - ~/docker/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - "/mnt/alien-storage-1/nextcloud:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.port=80"
      - "traefik.frontend.redirect.regex=^(.*)/nextcloud$$"
      - "traefik.frontend.redirect.replacement=$$1/nextcloud/"
      - "traefik.frontend.rule=PathPrefix: /nextcloud; ReplacePathRegex: ^/nextcloud/(.*) /$$1"
    environment:
      - TZ=${TZ}
      - MEMORY_LIMIT=512M
      - UPLOAD_MAX_SIZE=2048M
      - OPCACHE_MEM_SIZE=128
      - APC_SHM_SIZE=128M
      - DB_TYPE=mysql
      - DB_HOST=nextcloud-mariadb
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
```
