### ISSUE TITLE
Future docker compose file postgre?

### ISSUE THREAD

**Issue by killmasta93** [crazy-max/docker-nextcloud#95]
Hi 
I was wondering if its possible to add with postgre?
i was looking at the redis container would it be recommend to add also add this part for the cache?

```
 redis:
    image: redis:6-alpine
    container_name: nextcloud_redis
    environment:
      - "TZ"
    restart: always
     mem_limit: 2048m
    mem_reservation: 512m
```
